runtime: nodejs20
env: standard
instance_class: F1

handlers:
  - url: /.*
    script: auto
    secure: always
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_instances: 1
service_account: eksaq-utils@appspot.gserviceaccount.com